export const todaysEvents = [
  {
    id: 't1',
    title: 'Birthday Party',
    date: 'Today',
    time: '6:00 PM - 7:00 PM',
  image: require('../assets/images/birthday.png'),
    price: 'Free',
    badge: 'JOIN',
    description: 'A cheerful birthday celebration with music, decor, and good vibes.',
    booked: [
      { name: 'Anita P.' , time: '6:05 PM'},
      { name: 'Rajesh K.' , time: '6:10 PM'},
    ],
  },
  {
    id: 't2',
    title: 'BCC Conference Meeting',
    date: 'Today',
    time: '7:00 AM - 8:00 AM',
  image: require('../assets/images/conference.jpg'),
    price: 'Free',
    badge: 'FREE',
    description: 'Team presentations and discussions for the BCC conference agenda.',
    booked: [
      { name: 'Suresh T.' , time: '7:00 AM'},
    ],
  },
  {
    id: 't3',
    title: 'Kids Painting Workshop',
    date: 'Today',
    time: '4:00 PM - 5:30 PM',
  image: undefined,
    price: '$5',
    badge: 'BOOK',
    description: 'A fun painting workshop for kids aged 6-12. Materials included.',
    booked: [
      { name: 'Maya R.' , time: '4:02 PM'},
      { name: 'Irfan L.' , time: '4:07 PM'},
      { name: 'Zara M.' , time: '4:10 PM'},
    ],
  },
];

export const regularPrograms = [
  {
    id: 'r1',
    title: 'Zumba Dance Practice',
    time: '8:00 AM - 10:00 AM',
    image: require('../assets/images/zumba.png'),
    trainer: 'Aisha Khan',
    category: 'Celebration',
    coordinator: { name: 'Ajmal kalanad', role: 'New Co-Ordinator' },
    dateText: 'Sat, 1 Jan 2026, 10:30PM Onwards',
    venue: 'Lions Club New Year Eve',
    status: 'bookable',
    price: 'Free',
    badge: 'JOIN',
    description: 'High-energy Zumba sessions to keep you fit and energized. Drop-ins welcome.',
    booked: [
      { name: 'Nina V.' , time: '8:15 AM'},
      { name: 'Lalitha S.' , time: '8:20 AM'},
    ],
  },
  {
    id: 'r2',
    title: 'Yoga Class',
    time: '6:30 AM - 7:30 AM',
    image: require('../assets/images/yoga.jpg'),
    trainer: 'Rohit Menon',
    category: 'Celebration',
    coordinator: { name: 'Ajmal kalanad', role: 'New Co-Ordinator' },
    dateText: 'Sat, 1 Jan 2026, 10:30PM Onwards',
    venue: 'Lions Club New Year Eve',
    status: 'filled',
    price: 'Free',
    badge: 'JOIN',
    description: 'A calming yoga class focused on breath and flexibility. Suitable for all levels.',
    booked: [
      { name: 'Kiran D.' , time: '6:35 AM'},
      { name: 'Priya M.' , time: '6:37 AM'},
    ],
  },
  {
    id: 'r3',
    title: 'Chess Club',
    time: '6:00 PM - 8:00 PM',
    image: undefined,
    trainer: 'Coach Vivek',
    category: 'Celebration',
    coordinator: { name: 'Ajmal kalanad', role: 'New Co-Ordinator' },
    dateText: 'Sat, 1 Jan 2026, 10:30PM Onwards',
    venue: 'Lions Club New Year Eve',
    status: 'bookable',
    price: 'Free',
    badge: 'OPEN',
    description: 'Weekly chess club for all levels — coaching and friendly matches.',
    booked: [
      { name: 'Arun P.' , time: '6:05 PM'},
    ],
  },
  {
    id: 'r4',
    title: 'Pottery Basics',
    time: '2:00 PM - 4:00 PM',
    image: undefined,
    trainer: 'Meera Joshi',
    category: 'Celebration',
    coordinator: { name: 'Ajmal kalanad', role: 'New Co-Ordinator' },
    dateText: 'Sat, 1 Jan 2026, 10:30PM Onwards',
    venue: 'Lions Club New Year Eve',
    status: 'bookable',
    price: '$10',
    badge: 'BOOK',
    description: 'Learn pottery basics on the wheel. Small class size and hands-on guidance.',
    booked: [
      { name: 'Leena R.' , time: '2:10 PM'},
    ],
  },
];
